version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: catalog
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
